# ============================================
# CONFIGURACION DE SPRING BOOT
# ============================================

# 1. Configuracion de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/citas_medicas
spring.datasource.username=postgres
spring.datasource.password=515l3m4k3ll

# 2. Configuracion de JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# 3. Logging (para ver las consultas SQL)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# 4. Configuracion del servidor
server.port=8081
spring.main.allow-circular-references=true

# 5. Configuracion del Bot de Telegram
telegram.bot.username=CitasSalud_bot
telegram.bot.token=8563879473:AAGHd-Ut-cbYmHUW40GL9QWFGRHclMurmpA
clinica.direccion=Av. Eloy Alfaro 123, Quito - Ecuador

# ============================================
# CONFIGURACION DE JWT
# ============================================

# Secreto para firmar los tokens JWT (debe ser largo y seguro)
jwt.secret=MiClaveSecretaSuperSeguraParaJWT2026ConMasDe32Caracteres

# Tiempo de expiración del token en milisegundos (24 horas = 86400000)
jwt.expiration=86400000